kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '4'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"oxigraph:latest","namespace":"ldary24-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"oxigraph\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '1782038724'
  name: oxigraph
  uid: 4e5896b2-08e8-49df-9dea-cf47fd74b0b7
  creationTimestamp: '2022-11-29T21:29:30Z'
  generation: 13
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-29T21:34:42Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/route-disabled': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime-namespace': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"oxigraph"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/data"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:args': {}
                  'f:command': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":7878,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"graph-data"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-02T16:17:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: ldary24-dev
  labels:
    app: oxigraph
    app.kubernetes.io/component: oxigraph
    app.kubernetes.io/instance: oxigraph
    app.kubernetes.io/name: oxigraph
    app.kubernetes.io/part-of: graph-app
    app.openshift.io/runtime-namespace: ldary24-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxigraph
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oxigraph
        deployment: oxigraph
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: graph-data
          persistentVolumeClaim:
            claimName: graph-data
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: oxigraph
          command:
            - oxigraph_server
          ports:
            - containerPort: 7878
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: graph-data
              mountPath: /data
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/ldary24-dev/oxigraph@sha256:8ba12b976515e4b30ae844409c96e52b325268ae1f5e9a21e997f4e4459ec550
          args:
            - '--location'
            - /data
            - serve
            - '--bind'
            - '0.0.0.0:7878'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 13
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-12-02T16:16:27Z'
      lastTransitionTime: '2022-11-30T01:05:21Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "oxigraph-c65f87c9f" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-02T16:18:05Z'
      lastTransitionTime: '2022-12-02T16:18:05Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
